# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: baseconnect_backend_development
  host: 127.0.0.1
  port: 5432
  # If you created a local role in pgAdmin, uncomment:
  # username: jobs_user
  # password: jobs_pass

test:
  <<: *default
  database: baseconnect_backend_test
  host: 127.0.0.1
  port: 5432

# DO NOT inherit *default here (to avoid carrying host/user/password)
production:
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # sslmode: require   # optional; Herokuâ€™s DATABASE_URL usually includes SSL params
