# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: jobs_api_development
    host: 127.0.0.1
    port: 5432
    username: <%= ENV.fetch("PGUSER", "jobs_user") %>
    password: <%= ENV.fetch("PGPASSWORD", "jobs_pass") %>
  cable:
    <<: *default
    database: jobs_api_development
    host: 127.0.0.1
    port: 5432
    username: <%= ENV.fetch("PGUSER", "jobs_user") %>
    password: <%= ENV.fetch("PGPASSWORD", "jobs_pass") %>

test:
  primary:
    <<: *default
    database: jobs_api_development
    host: 127.0.0.1
    port: 5432
    username: <%= ENV.fetch("PGUSER", "jobs_user") %>
    password: <%= ENV.fetch("PGPASSWORD", "jobs_pass") %>
  cable:
    <<: *default
    database: jobs_api_development
    host: 127.0.0.1
    port: 5432
    username: <%= ENV.fetch("PGUSER", "jobs_user") %>
    password: <%= ENV.fetch("PGPASSWORD", "jobs_pass") %>

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cable:
    url: <%= ENV["SOLID_CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    pool: 5
